### ISSUE TITLE
Typo in \lib\modules\apostrophe-maintenance-mode-global\index.js

### ISSUE THREAD

**Issue by okfmohamed** [apostrophecms/apostrophe-maintenance-mode#3]
@boutell

- There is a typo in this module: https://www.npmjs.com/package/apostrophe-maintenance-mode in this file: \lib\modules\apostrophe-maintenance-mode-global\index.js

- Please fix it as it causes the arrange fields of other modules to default to the info tab under global. 

- Please see code below and notice the "arrangeFIelds" typo :
options.arrangeFields = (options.arrangeFIelds || []).concat([
{
name: 'maintenance',
label: 'Maintenance',
fields: [ 'maintenanceMode', 'maintenanceTitle', 'maintenanceMessage' ]
}
]);

**Comment by boutell** [comment]
Fix published 2.0.1 thanks
